version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  php:
    build:
      context: ./php
    volumes:
      - ./project:/var/www/html
    environment:
      PHP_PORT: ${PHP_PORT}
    depends_on:
      - db
  proxy:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

volumes:
  postgres_data:
