version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env

  php:
    ports:
      - "9000:9000"
    build:
      context: ./php
      target: dev
    volumes:
      - ../project:/var/www/html
    environment:
      PHP_PORT: ${PHP_PORT}
    depends_on:
      - db

  proxy:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - php