version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env

  php:
    container_name: php
    ports:
      - "9000:9000"
    build:
      context: ./php

    environment:
      PHP_PORT: ${PHP_PORT}
    depends_on:
      - db

  adminer:
    image: adminer:4.8.0
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
  proxy:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    restart: always

    depends_on:
      - php